/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InstancesRouteImport } from './routes/instances'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDiffRouteImport } from './routes/_app/diff'
import { Route as AppSessionIdRouteImport } from './routes/_app/session/$id'

const InstancesRoute = InstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDiffRoute = AppDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionIdRoute = AppSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AboutRoute
  '/instances': typeof InstancesRoute
  '/diff': typeof AppDiffRoute
  '/settings': typeof AppSettingsRoute
  '/session/$id': typeof AppSessionIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/instances': typeof InstancesRoute
  '/diff': typeof AppDiffRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/session/$id': typeof AppSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/instances': typeof InstancesRoute
  '/_app/diff': typeof AppDiffRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/session/$id': typeof AppSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/instances'
    | '/diff'
    | '/settings'
    | '/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/instances' | '/diff' | '/settings' | '/' | '/session/$id'
  id:
    | '__root__'
    | '/_app'
    | '/about'
    | '/instances'
    | '/_app/diff'
    | '/_app/settings'
    | '/_app/'
    | '/_app/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  InstancesRoute: typeof InstancesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/instances': {
      id: '/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof InstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diff': {
      id: '/_app/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof AppDiffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session/$id': {
      id: '/_app/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof AppSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDiffRoute: typeof AppDiffRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSessionIdRoute: typeof AppSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiffRoute: AppDiffRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSessionIdRoute: AppSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  InstancesRoute: InstancesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
